### ISSUE TITLE
Problem with data-verify-text in Rails 4 / Bootstrap 3

### ISSUE THREAD

**Issue by cmcguff** [ifad/data-confirm-modal#21]
I can get the verify box working, but I can't see how to get the verify-text option working in rails, i have the following without the label:

    <%= link_to('Delete', leave_type, title: 'Delete Transaction Type', data: { method: 'delete', verify: 'Yes', commit: "Yes, Delete it", confirm: "Are you sure you want to delete the Transaction Type for <b>#{leave_type.name}</b>?" })  %>

I'm a bit lost on how to get the verify-text option in there as Rails won't accept just putting verify-text: 'Type Yes to confirm' into this option.

**Comment by vjt** [comment]
Ciao @cmcguff, you should use `verify_text:`. Rails changes underscores to hyphens automatically when composing data attributes in HTML tags.

Cheers,

~Marcello

**Comment by vjt** [comment]
I've added this information to the README :-)
