### ISSUE TITLE
Change background of buttons

### ISSUE THREAD

**Issue by VladimirTS** [ifad/data-confirm-modal#24]
Does possibility exist to change background of buttons with options?

**Comment by vjt** [comment]
Not with options, but via CSS :)

**Comment by VladimirTS** [comment]
@vjt I tried, but can not override styles for buttons

**Comment by cschulte22** [comment]
You can change it with options - data-commit-class and data-cancel-class can be used to specify the bootstrap class for the button.  For example, this will you give you a bootstrap primary button (blue by default):

```ruby
<%= link_to "Not Dangerous", @item, class: 'btn btn-default', title: 'This is not scary', data: {confirm: 'Are you sure?', commit: 'Of Course', 'commit-class': 'btn-primary'} %>
```

**Comment by vjt** [comment]
Thanks, @cschulte22! :beers:

**Comment by adrianmann** [comment]
@cschulte22 Is there documentation for the classes you mentioned and any other ways of specifying styles in the confirm modal? I would like to change the size of the title text for example. Thanks.
