### ISSUE TITLE
Modal not show correct opacity

### ISSUE THREAD

**Issue by thiensubs** [ifad/data-confirm-modal#27]
![error](https://cloud.githubusercontent.com/assets/2623569/8700655/57a6f784-2b37-11e5-8a58-b203278521fc.png)
When confirm dialog show. It not show correct show dialog modal.
Please help me fix it.

**Comment by vjt** [comment]
Please try setting an higher `z-index` using the setDefaults call:

```js
dataConfirmModal.setDefaults({
  zIndex: 10059
});
```
