### ISSUE TITLE
Not Following Link After Confirm

### ISSUE THREAD

**Issue by jackerman09** [ifad/data-confirm-modal#30]
I am using rails, and after clicking the link and confirming it does not follow the link. Here's the link code:

    <td><%= link_to 'Cancel Appt', cancel_appointment_path(appointment), class: 'btn btn-default btn-xs btn-danger btn-disable-after-click', data: { confirm: "Are you sure you want to cancel the appointment?", commit: 'Yes', cancel: 'No' } %></td>

This is called `after_click` so that the button cannot accidentally be clicked twice by an impatient user:

    $('.btn-disable-after-click').on 'click', (e) ->
        $(this).addClass('disabled')

Also, I need to not disable the button if 'Cancel' is clicked. How can I implement this? How can I reference the modal's `after-confirm` or `after-cancel` events from javascript? What is the modal's class/id?

Thanks!

**Comment by vjt** [comment]
@jackerman09 - @sromocki kindly provided a fix this, does it fix the issue for you?

Thanks both!

**Comment by jackerman09** [comment]
@vjt Thanks for letting me know, but after I could not get that to work I switched to using this gem 'twitter-bootstrap-rails-confirm'.
