### ISSUE TITLE
Focus on the verify input

### ISSUE THREAD

**Issue by gauthier-delacroix** [ifad/data-confirm-modal#31]
Hi,

It would be nice to automatically focus on the verify input when opening a confirm modal with the verify feature !

**Comment by vjt** [comment]
Definitely makes sense.

**Comment by vjt** [comment]
This was actually a regression, now fixed. Thank you.

**Comment by gauthier-delacroix** [comment]
Doesn't seems to work on my side...

**Comment by vjt** [comment]
@gauthier-delacroix can you please post a [jsfiddle](https://jsfiddle.net/) reproducing the problem? Thanks :smile:

**Comment by vjt** [comment]
Here it is the jsfiddle: http://jsfiddle.net/8sduncgd/1/ and it looks working properly for me. Please reopen if it still doesn't work for you.
