### ISSUE TITLE
"form-control" as default for verifyClass

### ISSUE THREAD

**Issue by jdugarte** [ifad/data-confirm-modal#32]
First of all: thanks for this gem! I was about to build something similar when I found it 😁

I was wondering: why isn't "form-control" set as default for verifyClass, being this a bootstrap styled gem? I know I can set it like this:

dataConfirmModal.setDefaults({
    verifyClass: 'form-control',
});

but I would have thought this to be the default already, again, being this a bootstrap styled gem.

I was going to do a pull request with this, but I thought I ask first, in case there is something I'm missing here.

Thanks,

Jesús.-

**Comment by vjt** [comment]
That makes perfect sense. Done, thank you.

**Comment by jdugarte** [comment]
@vjt Thanks! 😁
