### ISSUE TITLE
Not working on Heroku

### ISSUE THREAD

**Issue by gilomen2** [ifad/data-confirm-modal#34]
This is working perfectly locally, but when pushed to Heroku, confirms are still using the browser default.

Herkou appears to have found the gem correctly:
``Using data-confirm-modal 1.1.0 from git://github.com/ifad/data-confirm-modal.git (at master)``

**Comment by gilomen2** [comment]
Sorry, the issue was with not having precompiled assets before pushing to Heroku.

**Comment by vjt** [comment]
ok, thanks anyway for taking the time to report. This issue is anyway gonna be useful for posterity stumbling upon the same problem :smile:
