### ISSUE TITLE
Implementation for Semantic-UI

### ISSUE THREAD

**Issue by kntmrkm** [ifad/data-confirm-modal#35]
I'm using this gem for bootstrap's project.

I like this gem, so I have forked for Semantic-UI.
http://semantic-ui.com

If you don't mind, add my forked gem to original README.

https://github.com/kntmrkm/data-confirm-modal-semantic-ui

thanks.

**Comment by vjt** [comment]
Hi @kntmrkm - what is your proposal in merging the two projects so to have a single codebase?

**Comment by kntmrkm** [comment]
It's just report to forked.
Not merge.
if add information for `Semantic-UI` to README. Semantic-ui user would notice existence of Semantic-ui version.

That's all.
