### ISSUE TITLE
Push to RubyGems?

### ISSUE THREAD

**Issue by Nekromancer** [ifad/data-confirm-modal#36]
Is there any option that you push that gem into RubyGems? I have very unfortuate server that can't do bundle install if there are any dependencies directly from git (some kind of git error. And git binaries are quite old...)

**Comment by trautwein** [comment]
I just published the Gem on RubyGems, see https://rubygems.org/gems/data-confirm-modal

Hope you're fine with that. Please let me know if you want to take over ownership.

**Comment by vjt** [comment]
Thanks, man. Yes, please, can you add `vjt at openssl dot it` as an owner? :beers:

**Comment by trautwein** [comment]
Done! 👍

**Comment by vjt** [comment]
Thanks! Pushed the new v1.2.0 :-)
