### ISSUE TITLE
data-title not working

### ISSUE THREAD

**Issue by pakkawat** [ifad/data-confirm-modal#40]
I try to set title with this code `<%= link_to 'Delete', data: {title: "test", confirm: 'Are you sure?'} %>`
It not work and alway show "Are you sure?"
So i looking in your code and i suspect this line 

`title:        element.attr('title') || element.data('original-title')`

Then i test it with this code `<%= link_to 'Delete', title: "test", data: {confirm: 'Are you sure?'} %>` and it work

sorry about my english language

**Comment by dapicester** [comment]
That is exactly how it is supposed to work. In fact from the README:
> The modal's title will be get from the link's `title` attribute value.
> The modal text will be taken from the `data-confirm` value.

**Comment by vjt** [comment]
That's correct. I have nothing against adding `data-title`, though, but I'd like some input from other users first.

Thanks for reporting! 😃

**Comment by dapicester** [comment]
I bumped into this yesterday and my use case is the following:

I use `title` attribute to show a tooltip (actually using Bootstrap):
```haml
%li
  = link_to some_path, method: :post, title: t('.title'),
    data: { confirm: t('.confirm'), toggle: 'tooltip' }
```
In the code above `title` would be used for the tooltip text _and_ the modal title, which is not what I want.

So I ended up adding the tooltip to the wrapper element:
```haml
%li{title: t('.title'), data: { toggle: 'tooltip' }}
  = link_to some_path, method: :post,
    title: t('.modal-title'), data: { confirm: t('.confirm') }
```

While this works fine, it would be very useful if one could set the modal title using the `data-title` attribute.

**Comment by westonganger** [comment]
+1

**Comment by lucaspiller** [comment]
If anyone would like this implemented, feel free to send a PR, and you'll get magic points!
