### ISSUE TITLE
Version 1.3.0?

### ISSUE THREAD

**Issue by 6temes** [ifad/data-confirm-modal#48]
The master branch of the gem has a feature that allows the class of the modal to be selected using a `data attribute`:

https://github.com/ifad/data-confirm-modal/blob/master/vendor/assets/javascripts/data-confirm-modal.js#L98

Apparently, it was introduced after the release of v. 1.2.0 but, in my opinion, this feature is important enough to deserve its own version.

Would it be possible to release it to RubyGems?

**Comment by vjt** [comment]
Hi @6temes,

thanks for the heads up. Version 1.3.0 has been [pushed to RubyGems](https://rubygems.org/gems/data-confirm-modal/versions/1.3.0).

Cheers,
