### ISSUE TITLE
Duplicate alert rails 5

### ISSUE THREAD

**Issue by Mesnet** [ifad/data-confirm-modal#50]
Hi guys, thanks for this gem I love it !! 
I've just updated to rails 5 and I'm encountering a problem since that. The template is working but when I click on continue, the default modal (not deigned) appear. So I have to click two times on validate. Someone has already had the same problem ?

**Comment by haurbano** [comment]
Hi @Mesnet, I have the same issue, do you found a solution? whether yes, plese tell me it! :D

**Comment by mvdamme** [comment]
Same problem here...

**Comment by mvdamme** [comment]
It turns out that data-confirm-modal is not adapted to the new rails-ujs used in Rails 5. 
I reverted to using jquery-ujs which fixed the problem (and since I'm using jQuery anyway it comes without overhead).

**Comment by SunDi3yansyah** [comment]
Yay!

`application.js` should be like this

```
//= require jquery
//= require jquery_ujs
```

maybe **Rails > 5.1** because use `rails-ujs`

Thanks @mvdamme :+1:

**Comment by CyberDeck** [comment]
To get it working with `rails-ujs` for Rails 5.1, you can give it a try with my pull request #55.

**Comment by vjt** [comment]
Fixed in #55. Thanks everyone.
