### ISSUE TITLE
Bootstrap 4 support?

### ISSUE THREAD

**Issue by rkbhochalya** [ifad/data-confirm-modal#56]
I tried to use it with Rails 5.1 and Bootstrap 4 but the default alert messages is showing instead of the modal. There are no JS errors in the console. Do you have any plan to support Bootstrap 4 and Rails 5?

**Comment by CyberDeck** [comment]
You can try out my pull request #55. Please share your opinions on it. So far no update from official maintainer.

**Comment by vjt** [comment]
Fixed in #55. Thanks everyone!

**Comment by archonic** [comment]
I'm not seeing support for BS4. The modalClass argument ends up colouring the whole background and the title is on the right. Is BS4 support in the roadmap?

![limestone](https://user-images.githubusercontent.com/588846/31579763-3ea47f0c-b0f2-11e7-9473-29f3b29f3c7e.png)

It would be nice to have a template override for the HTML of the modal so we could spin our own support and make any mods we want.
