### ISSUE TITLE
v1.5.0 break Bootstrap 3 modals

### ISSUE THREAD

**Issue by Varek** [ifad/data-confirm-modal#59]
Hi, thanks for this gem, it made replacing confirm alerts with modals a breeze.

The latest version brought Rails 5 and Bootstrap 4 support. In the pull #55 you where wondering about the backward compatibility and said that everything is fine. But I noticed the Bootstrap 4 modal change break the Bootstrap 3 modals. 
v1.5.0 with Bootstrap 3 looks like this: ![Broken Bootstrap 3 modal](https://d.pr/i/Mm3Mox+)
Here a jsfiddle(your example with the latest version) to demonstrate: http://jsfiddle.net/ze2Lz8tm/56/

Downgrading solved it for me, but maybe you should create a Bootstrap 3 compatible version and add a notice in the readme.

**Comment by vjt** [comment]
Thanks for the report. I will look into this. Sorry for the inconvenience.

**Comment by vjt** [comment]
Hi,

issue fixed and new version released as 1.6.0.

Cheers,
