### ISSUE TITLE
Does it work with rails 5.1 and Bootstrap 4?

### ISSUE THREAD

**Issue by ketysek** [ifad/data-confirm-modal#63]
Hi, I've installed your library, then I've pasted it in application.js

`//= require jquery3
//= require popper
//= require bootstrap
//= require data-confirm-modal`

but it doesn't work. Every time I'm getting old, browser window just like without using your lib. Console is clear, without errors.

**Comment by mgrubb** [comment]
same here

**Comment by vjt** [comment]
Will check this out asap.

**Comment by mgrubb** [comment]
The latest HEAD from github works, but the Gem release (1.6.1) doesn't.  I'm guessing it's because the fix for issue #61 isn't included in that release.

**Comment by vjt** [comment]
Thanks for the feedback. I will cut a new release today.

~Marcello
-- 
~ vjt@openssl.it
~ http://sindro.me/

**Comment by vjt** [comment]
Released [v1.6.2](https://github.com/ifad/data-confirm-modal/tree/v1.6.2) on [RubyGems](https://rubygems.org/gems/data-confirm-modal/versions/1.6.2) and [npm](https://www.npmjs.com/package/data-confirm-modal).

Please reopen if you still encounter issues.

Thanks!
